spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: lldj123414
    url: jdbc:mariadb://dev-db-1.cym4iarmfcfz.ap-northeast-2.rds.amazonaws.com:3306/example?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    slaves:
      slave1:
        name: slave1
        driver-class-name: org.mariadb.jdbc.Driver
        username: admin
        password: lldj123414
        url: jdbc:mariadb://dev-db-2.cym4iarmfcfz.ap-northeast-2.rds.amazonaws.com:3306/example?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        hbm2ddl:
          auto: create
